import './globals.css'
import { Poppins } from 'next/font/google';
import Header from './components/Header';

export const metadata = {
  title: 'TK - App tile',
  description: 'Generated by create next app',
  keywords: "tk, tkwebdev"
}

const poppins = Poppins({
    weight: ['400', '700'],
    subsets: ["latin"]
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        suppressHydrationWarning = {true}
        className={poppins.className}
      >
        <Header />
        <main className='container'>
            {children}
        </main>
      </body>
    </html>
  )
}
